apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: agri-app-rs
  name: svc-agri-app-rs
spec:
  ports:
  - port: 8001
    protocol: TCP
    targetPort: 8001
  selector:
    app: agri-app-rs
