apiVersion: v1
kind: PersistentVolume
metadata:
  name: readings-pv
spec:
  storageClassName: agri-store
  capacity:
    storage: 600Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/agri-app"